runtime: python39

default_expiration: "1d 1h"

handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html
  secure: always
  
- url: /(.*)
  static_files: www/\1
  upload: www/(.*)
  secure: always
  